import os
import opendbc

Import('env')

opendbc_path = opendbc.INCLUDE_PATH

libpanda_srcs = [
  'panda.c',
  '../../board/main_definitions.c',
  '../../board/fake_stm.c',
  '../../board/drivers/can_common.c',
  '../../board/can_comms.c',
  '../../board/utils.c',
  '../../board/libc.c',
  '../../board/safety_definitions.c',
  '../../board/safety_mode_wrapper.c',
]

env = env.Clone()
env.Append(CPPPATH=['#', '.', '#board', opendbc_path])
env.Append(CCFLAGS=['-nostdlib', '-fno-builtin', '-std=gnu11', '-Wfatal-errors', '-Wno-pointer-to-int-cast'])

libpanda = env.SharedLibrary('libpanda', libpanda_srcs)
Return('libpanda')
